### ISSUE TITLE
OSError:  [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MrMastodonFarm** [TomWhitwell/SlowMovie#20]
Hi all, I'm a Pi newbie bumbling my way through this project.  I managed to get the software installed and my e-ink screen connected, and am able to successfully run epd_7in5_V2_test.py.  

When I run helloworld.py or slowmovie.py, the screen cycles briefly between all black and all white, and then the script terminates with the following error:

```
/home/pi/SlowMovie/Videos/test.mp4
Traceback (most recent call last):
File "helloworld.py", line 57, in <module>
    frameCount = int(ffmpeg.probe(inputVid)['streams'][0]['nb_frames'])
File "/usr/local/lib/python2.7/dist-packages/ffmpeg/_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I would be greatful for any thoughts on what might be going wrong here.  Thanks in advance!

**Comment by MrMastodonFarm** [comment]
Figured it out--I guess there was something wrong with my ffmpeg install, as reinstalling fixed the problem.  I can now run the helloworld script and get images on the screen.

**Comment by MrMastodonFarm** [comment]
Figured it out--I guess there was something wrong with my ffmpeg install, as reinstalling fixed the problem. I can now run the helloworld script and get images on the screen.
